### ISSUE TITLE
Unable to install because of outdated documentation

### ISSUE THREAD

**Issue by bitbreakr** [CloudFire-LLC/cloudfire#1033]
I've tried to install firezone on DigitalOcean following the official doc:

https://docs.firezone.dev/deploy/docker/

It is impossible to install firezone.

Step **gen-cert** is not working because the gen-cert certificate is missing (not inside the container)
> docker-compose run --rm firezone bin/gen-cert

Step **create-or-reset-admin** is not working  
> docker compose run --rm firezone bin/create-or-reset-admin

I get the following:

```shell
WARNING: The following deploy sub-keys are not supported and have been ignored: update_config, restart_policy.delay, restart_policy.window
Creating root_firezone_run ... done
--rpc-eval : RPC failed with reason :nodedown
```

**Comment by reciproco** [comment]
I was able to install replacing:
docker compose run --rm firezone bin/create-or-reset-admin
with
docker exec firezone bin/create-or-reset-admin

The web interface seems to work but i have the following errors in the firezone logs:
dc logs -f --tail=200 firezone
Attaching to firezone_firezone_1
firezone_1  | ip: can't find device 'wg-firezone'
firezone_1  | ip: RTNETLINK answers: Not supported
firezone_1  | ip: invalid argument 'up' to 'mtu'
firezone_1  | ip: RTNETLINK answers: Network is down

**Comment by jamilbk** [comment]
Thanks for the report @reciproco! Could I get a little info about how you installed Firezone? Are you using the docker installation script?

**Comment by reciproco** [comment]
> Thanks for the report @reciproco! Could I get a little info about how you installed Firezone? Are you using the docker installation script?

Of course. No, I follow the manual install option  (https://docs.firezone.dev/deploy/docker) on Ubuntu 20.04.5 LTS
, but not literally. I use a customized docker-compose.yml and then execute:
```
docker run --rm firezone/firezone bin/gen-env > .env (set EXTERNAL_URL and ADMIN_EMAIL)
docker-compose up -d
docker exec firezone bin/create-or-reset-admin
```

This is my customized docker-compose.yml:
```version: '3.7'

networks:
  traefik_proxy:
    external: true
  web:

services:
  firezone:
    image: firezone/firezone
    ports:
      - 51820:51820/udp
    env_file:
      # This should contain a list of env vars for configuring Firezone.
      # See https://docs.firezone.dev/reference/env-vars for more info.
      - .env
    volumes:
      # IMPORTANT: Persists WireGuard private key and other data. If
      # /var/firezone/private_key exists when Firezone starts, it is
      # used as the WireGuard private. Otherwise, one is generated.
      - ./volumes/data/firezone/firezone:/var/firezone
    cap_add:
      # Needed for WireGuard and firewall support.
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      # Needed for masquerading and NAT.
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    networks:
      - traefik_proxy
      - web
    labels:
      - "traefik.http.routers.web-${TRAEFIK_CONTAINER_NAME}.rule=${TRAEFIK_FRONTEND_RULE}"
      - "traefik.http.routers.web-${TRAEFIK_CONTAINER_NAME}.tls.certresolver=default"
      - "traefik.http.routers.web-${TRAEFIK_CONTAINER_NAME}.tls.options=Options@file"
      - "traefik.http.routers.web-${TRAEFIK_CONTAINER_NAME}.middlewares=secure-headers@file"
      - "traefik.enable=true"
      - "traefik.http.services.web-service-${TRAEFIK_CONTAINER_NAME}.loadbalancer.server.port=13000"
      - "traefik.http.services.web-service-${TRAEFIK_CONTAINER_NAME}.loadbalancer.server.scheme=http"
      - "traefik.http.services.web-service-${TRAEFIK_CONTAINER_NAME}.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.web-service-${TRAEFIK_CONTAINER_NAME}.loadbalancer.sticky.cookie.httpOnly=true"
      - "traefik.http.services.web-service-${TRAEFIK_CONTAINER_NAME}.loadbalancer.sticky.cookie.secure=true"

    depends_on:
      - postgres

  postgres:
    image: postgres:15
    volumes:
      - ./volumes/data/firezone/postgres:/var/lib/postgresql/data
    networks:
      - web
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-firezone}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?err}

```

Thanks to you

**Comment by jamilbk** [comment]
Thanks for the info. Will be fixed in 0.6.3 imminently.

**Comment by jamilbk** [comment]
In the meantime, if you set the following ENV vars for the firezone container, that should fix the issue:

```env
WIREGUARD_INTERFACE_NAME=wg-firezone
WIREGUARD_IPV4_ADDRESS=10.3.2.1
WIREGUARD_IPV4_ENABLED=true
WIREGUARD_IPV4_NETWORK=10.3.2.0/24
WIREGUARD_IPV6_ADDRESS=fd00::3:2:1
WIREGUARD_IPV6_ENABLED=true
WIREGUARD_IPV6_NETWORK=fd00::3:2:0/120
WIREGUARD_MTU=1280
```

**Comment by reciproco** [comment]
Thanks, now it is working. But I had some problems with the wireguard device creation

**Comment by jamilbk** [comment]
@reciproco Give 0.6.3 a try and let me know if that fixes your issue. You can upgrade with:

```
docker compose pull
docker compose up -d
```

**Comment by tezakaftor** [comment]
Hi!
I'm still getting the error ip: can't find device 'wg-firezone' in 0.6.3 with/or without WIREGUARD_INTERFACE_NAME=wg-firezone in the .env file.

**Comment by jamilbk** [comment]
Hi @tezakaftor -- that error may be a red herring. See https://github.com/firezone/firezone/blob/master/rel/overlays/bin/server#L15 -- we always check for the interface name before creating. I'll update the script to swallow the error so it's not confusing.

**Comment by ilyatovbin-pp** [comment]
the script installation is broken(ish) as well..
"curl -fsSL https://github.com/firezone/firezone/raw/master/scripts/install.sh | bash -E" does nothing and exits after a second..
downloading and manually executing the script starts the inputs but then:
1. the desired install directory defaults to $HOME which is weird.
2. selecting a separate folder does not create it and the script exists on "No such file or directory"
3. selecting "No" on the "ssl certificate provisioning" still runs caddy container. I want to provision certs by myself so I don't need this. also now I can't actually find the docs for using docker and manually adding certs. am I forced to use caddy?

after that the install works..

p.s
you should add an input allowing customers to opt out of telemetry during installation since I've seen it's defaulted to "true" in  https://docs.firezone.dev/reference/env-vars/

--EDIT--
uninstall script is broken as well. looks like it's meant for the non-docker version only.

**Comment by reciproco** [comment]
> @reciproco Give 0.6.3 a try and let me know if that fixes your issue. You can upgrade with:
> 
> ```
> docker compose pull
> docker compose up -d
> ```

I did it and I see no errors on the logs

Thanks

**Comment by jamilbk** [comment]
> the script installation is broken(ish) as well.. "curl -fsSL https://github.com/firezone/firezone/raw/master/scripts/install.sh | bash -E" does nothing and exits after a second.. downloading and manually executing the script starts the inputs but then:
> 
> 1. the desired install directory defaults to $HOME which is weird.
> 2. selecting a separate folder does not create it and the script exists on "No such file or directory"
> 3. selecting "No" on the "ssl certificate provisioning" still runs caddy container. I want to provision certs by myself so I don't need this. also now I can't actually find the docs for using docker and manually adding certs. am I forced to use caddy?
> 
> after that the install works..
> 
> p.s you should add an input allowing customers to opt out of telemetry during installation since I've seen it's defaulted to "true" in https://docs.firezone.dev/reference/env-vars/
> 
> --EDIT-- uninstall script is broken as well. looks like it's meant for the non-docker version only.

Thanks for the report. Working on fixes to the above.
