### ISSUE TITLE
We cannot deploy gateways anymore.... Please help

### ISSUE THREAD

**Issue by heathprovost** [CloudFire-LLC/cloudfire#8471]
#### Describe the bug

Tried to do instance refreshes on our gateways, get this error when the systemd service is starting

```
firezone-gateway.service - Firezone Gateway
   Loaded: loaded (/etc/systemd/system/firezone-gateway.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2025-03-17 16:04:03 UTC; 2s ago
     Docs: https://www.firezone.dev/kb
  Process: 3195 PreExecStart=/usr/local/bin/firezone-gateway-init (code=exited, status=226/NAMESPACE)
 Main PID: 3195 (code=exited, status=226/NAMESPACE)
```

tried manually running the init to download the binary, which works. I chown'd it to firezone:firezone and set the permossions to 0755 and removed the PreExecStart from the service file. Then I get this:

```
firezone-gateway.service - Firezone Gateway
   Loaded: loaded (/etc/systemd/system/firezone-gateway.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2025-03-17 16:04:03 UTC; 2s ago
     Docs: https://www.firezone.dev/kb
  Process: 3195 ExecStart=/usr/local/bin/firezone-gateway (code=exited, status=226/NAMESPACE)
 Main PID: 3195 (code=exited, status=226/NAMESPACE)
```

~~Please help. We are dead in the water and I have 15 people who cannot work... Seems like some kind of permissions thing but I have no idea what the cause could be. The way we deployed these has worked fine for months now and suddenly boom...~~ Found a manual workaround - see comments

#### To Reproduce

Install gateway using standard process.

#### Expected behavior

Gateway starts

#### Screenshots / Logs

_If applicable, add screenshots and log traces to help debug your problem **with
any sensitive data removed**._

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal): Gateway
- _Firezone Version (e.g. 1.0.0 or N/A): 1.4.5
- _OS and version: (e.g. Ubuntu 22.04 or N/A): AWS Linux 2
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A): Systemd

#### Additional context

Account ID if it helps: e4047728-3b5e-463c-b10d-ffdf22c6ddb3

**Comment by heathprovost** [comment]
If it is possible that there is a manual fix I can do on my end to just get the gateway to spin up I would be happy with that for now...

**Comment by heathprovost** [comment]
Well I figured out that this commit broke it for us: https://github.com/firezone/firezone/pull/8120

I ran those 3 lines that were removed and everything started working...

Issue must have something to do with the change to using StateDirectory to have systemd create /var/lib/firezone, but honestly I just dont know enough about systemd to help troubleshoot this much more than that. 

I will be monitoring this issue closely so if someone needs me to do something just ask. This is not the level of fire for us that is was, but we still want to fix this asap because we cannot update our gateways without manual intervention until this is fixed.

**Comment by jamilbk** [comment]
Thanks for the info. Likely your systemd version is not new enough to support those lines. They were added recently to harden the systemd installation. We actually don't use the `/var/lib/firezone` if the `FIREZONE_ID` variable is provided, so I'll look into removing that section entirely.

**Comment by heathprovost** [comment]
We are not currently providing FIREZONE_ID when we set stuff up... Should we? We are on systemd v219, seems like StateDirectory was added in v235 :(

I see this in the terraform templates... 

```
FIREZONE_ID=$(echo $RANDOM$(hostname) | md5sum | head -c 20; echo;)
```

Should we be doing something like that in our userdata scripts to set it? We are not using docker or terraform, we wrote our own CDK for this and chose to just use the systemd deployment method.

**Comment by jamilbk** [comment]
You'll need either FIREZONE_ID provided or a writeable /var/lib/firezone directory - the issue here is that the systemd install script unconditionally creates /var/lib/firezone when we should probably be populating FIREZONE_ID in our script instead, since StateDirectory is not supported.

That would eliminate the need for you to have to worry about this at all and continue using the systemd script as is.

**Comment by jamilbk** [comment]
I'm just landing from a flight - will have a fix pushed out in a few hours.

**Comment by heathprovost** [comment]
I just looked at your PR. Assuming us doing this on 1st boot up of our instances would work once this is in main?

```
FIREZONE_TOKEN="$firezoneToken" FIREZONE_ID="$(uuidgen)" bash <(curl -fsSL https://raw.githubusercontent.com/firezone/firezone/main/scripts/gateway-systemd-install.sh)
```

Our instances have uuidgen on them so seems like that would work to me. Also THANK YOU!

**Comment by jamilbk** [comment]
Yes it should.

**Comment by jamilbk** [comment]
This has been deployed to production.

**Comment by heathprovost** [comment]
So I just tested this out and I am still having issues, although for now I have worked around them...

The script `/usr/local/bin/firezone-gateway-init` does not work on my instances when run from the systemd service. I get failures related to permissions. In order for any of this to work now for me, I have to do the following:

1. run `/usr/local/bin/firezone-gateway-init` as root
2. Then remove the `ExecStartPre` from the systemd service file

This works, but Im not sure that it would work in the event that a restart of the service is needed... That is not something that ever happens with our deployments normally (we essentially do instance replacements every time we want to deploy these).

I can try to get something setup to test this more maybe this weekend, but I don't have time for the remainder of the week so at this point Im just rolling with what I did above. 

I definitely think there is something still going wrong somewhere, however. Its probably due to our use of AWS Linux 2 (which is old). I tried to do this on AWS Linux 2023 instead (the current latest supported version) and while everything **appears** to work it actually doesn't. Ill try to setup my testing scenerio using this since it is what we would prefer to run on anyway.

**Comment by jamilbk** [comment]
Thanks for the report @heathprovost - we'll setup an Amazon Linux 2 testbed internally to troubleshoot this further. Reopening.

**Comment by jamilbk** [comment]
This PR should fix the issue: https://github.com/firezone/firezone/pull/8480

**Comment by heathprovost** [comment]
Ill try to test asap. Do you guys test Amazon Linux 2023? I would move to that one if firezone worked on it, but it never has. I honestly don't know why though, because it does not produce the same kind of errors. Like the service starts and seems to work, but things don't actually work (i.e. I cannot connect to resources from clients). I just never revisited it...

Im only mentioning because Amazon Linux 2023 has systemd v252 so all that stuff you guys did seems to work fine on it, its something else that is going wrong. That and it is the currently most widely used linux distro on AWS, so its what most folks use by default.

I tried once today but it seemed to have the same behavior as it did back when I tried the first time, it starts up fine and says its running but nothing can connect to anything...

**Comment by heathprovost** [comment]
I was able to deploy on AWS Linux 2 with no issues using `https://raw.githubusercontent.com/firezone/firezone/refs/heads/fix/systemd-install/scripts/gateway-systemd-install.sh`

**Comment by jamilbk** [comment]
Opened a new issue to investigate Amazon Linux 2023: https://github.com/firezone/firezone/issues/8481
